oauth2:
  client:
    clientId: app
    clientSecret: somesecret
    tokenUri: http://wv4-demo-login.cfapps.digitalglobe.com/oauth/token
    authorizationUri: http://wv4-demo-login.cfapps.digitalglobe.com/oauth/authorize
  resource:
    userInfoUri: http://wv4-demo-uaa.cfapps.digitalglobe.com/userinfo
    preferTokenInfo: false
  sso:
    loginPath: http://wv4-demo-login.cfapps.digitalglobe.com 
    logoutPath: http://wv4-demo-login.cfapps.digitalglobe.com/logout.do

demoapp:
  url: http://wv4-demo-sso.cfapps.digitalglobe.com
  loginUrl: http://wv4-demo-login.cfapps.digitalglobe.com